### ISSUE TITLE
Allow posting compendia only for a specific user level

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-muncher#21]
- [x] implement user levels on registration in o2r-bouncer
- [x] implement "`100` or higher" for `POST`ing new compendia
- [x] document manual change of user level using direct DB access

**Comment by JanKoppe** [comment]
Duplicate Issue? https://github.com/o2r-project/o2r-muncher/issues/20

**Comment by nuest** [comment]
The default level is `0` in the bouncer already. Let's keep it at that.

The changes are in https://github.com/nuest/o2r-muncher/tree/userlevels
