### ISSUE TITLE
Add throttling to bagtainer jobs

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-muncher#29]
the jobs running containers should not slow down other containers on the system, especially on non-distributed demo servers...

the throttling could even depend on user level :-)

**Comment by JanKoppe** [comment]
__Image Building__

https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/build-image-from-a-dockerfile →
```
[...]
cpushares - CPU shares (relative weight).
cpusetcpus - CPUs in which to allow execution (e.g., 0-3, 0,1).
cpuperiod - The length of a CPU period in microseconds.
cpuquota - Microseconds of CPU time that the container can get in a CPU period.
[...]
```
A combination of these options could be passed along in [executor.js, line 204](https://github.com/o2r-project/o2r-muncher/blob/master/lib/executor.js#L204). Those options aren't very intuitive though.

__Container execution__

https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/create-a-container →

```
[...]
         "CpuPercent": 80,
         "CpuShares": 512,
         "CpuPeriod": 100000,
         "CpuQuota": 50000,
[...]
```
One or more of these options can be passed allong in the fourth argument (currently `''`) to docker.run in [executor.js, line 256](https://github.com/o2r-project/o2r-muncher/blob/master/lib/executor.js#L256). I would try `CpuPercent` first.

**Comment by nuest** [comment]
Thanks for the pointers!

While I am at it, I could also add an execution queue... no real sense in limiting CPU share if there can be an arbitrary number of containers.

**Comment by nuest** [comment]
- [ ] limit memory to `1G` and leave swap to default (i.e. double the memory)
- [ ] limit cpu to at most 25 % of cpu shares if all containers want 100%... this should ideally be relative to the number of bagtainers already running. But since the services containers run with default shares, they should take precedence over the bagtainers with this setting.
