### ISSUE TITLE
Add filters for user and status to job endpoint

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-muncher#30]
The [job endpoint](http://o2r.info/o2r-web-api/job/#list-jobs) must be extended with filters for user (to show "my jobs" on the user page) and status (to show a list of running jobs).
- [x] jobs can be filtered by user
- [x] jobs can be filtered by status
  - if any of the steps is running, the job is `running`
  - if all of the steps are completed, the job is `completed`
  - if none of the steps is running, the job is `queued`

**Comment by LukasLohoff** [comment]
fixed in https://github.com/o2r-project/o2r-muncher/pull/44
