### ISSUE TITLE
Compendium filter by DOI

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-muncher#48]
Now that DOIs are extracted during upload, see https://github.com/o2r-project/o2r-meta/issues/28#event-1076304145, we can add a filter to the compendium endpoint to retrieve specific compendia based on their DOI.

**Comment by 7048730** [comment]
note that `identifier.doi` can still be `null` if retrieval from the paper source and the registry fails. the key is only available when the user has checked and completed this field of the MD or selected to prereserve a doi via 3rd party repository (not yet implemented).

**Comment by LukasLohoff** [comment]
@nuest Can be closed with #49
