### ISSUE TITLE
Add basic R installation and expose R_HOME to support RData analysis during extraction

### ISSUE THREAD

**Issue by 7048730** [o2r-project/o2r-muncher#53]
After an exciting journey to the rdata file format, I gave up on it and started creating suitable previews by calling R itself.
Could you add a base R to the image and make sure R_HOME env has the path to the executable?

**Comment by nuest** [comment]
No I cannot. The app image should not contain R. But it should be simple enough to spin up a container to do that. Though then the question is how to get that information into meta.

Is your plan to use some R to Python bridge?



I also thought this feature was not so important, but I'd be happy to help with with soon.

**Comment by 7048730** [comment]
If we add R container, I'm not sure how to access R_HOME.
Well, I could add R to o2rmeta but it will force another licence, I guess.

The feature is important from a user's point of view, I now agree that interacting with a cryptic rdata, e.g. as a reviewer is a bad experienece whereas having a preview of it can greatly contribute to get a grip on the underlaying data...

**Comment by nuest** [comment]
I understand the importance for the reader, point taken.

So, read it via pipe back to Python. Do you already have an idea for the R code you would call and the Python code to read it? I would like to give it an hour trying out if the works the way I think, and those snippets would help me a lot.

**Comment by 7048730** [comment]
Yes, its ready, I'm doing the tests now. I just pass the rdata file and call `ls.str()`. The only hurdle is to get access to the R executable, i. e. pass full path to the extractor or enable it to read it out somewhere.

**Comment by 7048730** [comment]
This build includes it de9c51235064f493e0ca5a43393281e75c457097

**Comment by nuest** [comment]
How about (test file is in Sciebo sandbox)

```bash
$ docker run -it --rm -v $(pwd)/test_for_meta.RData:/.RData:ro rocker/r-base:latest Rscript -e "load('/.RData'); ls.str()"
aclass : Formal class 'classGeneratorFunction' [package "methods"] with 3 slots
answer :  num 42
f : function (x)  
l : List of 7
 $ : chr "a list"
 $ : chr "of"
 $ : chr "strings and some"
 $ : num 1
 $ : num 1.1
 $ : num 1.2
 $ : chr "some numbers"
string :  chr "this is a test"
```

**Comment by nuest** [comment]
I also got things to work with the pipe, tested in interactive Python console:

```Python
$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from subprocess import Popen, PIPE, STDOUT
>>> p = Popen(['docker', 'run', '-i', '--rm', '-v', '/home/daniel/ownCloud/o2r-data/sandbox/test_for_meta.RData:/.RData:ro', 'rocker/r-base:latest', 'R', '--no-save'], stdout=PIPE, stdin=PIPE, stderr=STDOUT)
>>> p.communicate(input=b'ls.str()')[0].decode('ISO-8859-1')[:-4].split("> ls.str()")[1]u'\naclass : Formal class \'classGeneratorFunction\' [package "methods"] with 3 slots\nanswer :  num 42\nf : function (x)  \nl : List of 7\n $ : chr "a list"\n $ : chr "of"\n $ : chr "strings and some"\n $ : num 1\n $ : num 1.1\n $ : num 1.2\n $ : chr "some numbers"\nstring :  chr "this is a test"'
```

**Comment by 7048730** [comment]
I'd prefer to have a environment agnostic solution as far as possible. Is there a way of testing if Docker (rocker) is available? So that my app remains working as stand alone (i.e. non o2r-context).
Anyway we can do this like this for the time.

**Comment by nuest** [comment]
`docker --version` to test, and if it is there, then rocker is there or will be downloaded (if there is no internet connection, then other extraction stuff also does not work, do you test connectivity for those already?).

**Comment by 7048730** [comment]
the extractor does not test for internet connectivity. it can be started with `-xo` to switch off all http tries. if not switched and still no internet connectivity, it will state exceptions.

**Comment by nuest** [comment]
So will you disable RData extraction when `-xo` is active?

**Comment by 7048730** [comment]
well, I have to call parse RData for every .rdata file that the extractor encounters (potentially hundreds of them). If you want to go for the docker solutions is could be handy to check if the docker r installation is available, pull it once if not `-xo` and else skip it. Ofc it would be much easier to have access to R without docker and without need to internet connection. So there is still the option to add r-base to o2r meta.
We should discuss this next meeting...

**Comment by nuest** [comment]
We can discuss it, but if we have hundreds of .RData files, then calling R directly vs. calling R in a container might or might not make a difference, we will probably never learn that. I suggest to have a working version for what we actually have in our test data.

**Comment by 7048730** [comment]
This feature cannot be used unless R_HOME plus r base is available. If you want to skip this for the moment, the issue can be closed...

**Comment by nuest** [comment]
I prefer to skip this for the moment and keep the issue _open_.

**Comment by 7048730** [comment]
Okay, I prefer to remove rdata handling for the moment then, in order to keep things clean! I will leave a parse stub, in case anyone wants to continue there

**Comment by nuest** [comment]
Now that meta runs in its own container, which is [based on Debian](https://github.com/o2r-project/o2r-meta/blob/dev/Dockerfile) we could easily add R to the image and revisit this.

**Comment by 7048730** [comment]
okay, what's better: adding R to Debian oder adding python stuff to rocker?

**Comment by nuest** [comment]
I would say the _primary_ software in the container is Python, and meta tools should still work if R is broken. So I suggest to install R into the base image we use now. Based on `rocker/base`'s Dockerfile, I'd say (untested) the following should suffice (maybe [littler](https://cran.r-project.org/web/packages/littler/vignettes/littler-examples.html) could be interesting):

```Dockerfile
## based on https://github.com/rocker-org/rocker/blob/master/r-base/Dockerfile
## Use Debian unstable via pinning -- new style via APT::Default-Release
RUN echo "deb http://http.debian.net/debian sid main" > /etc/apt/sources.list.d/debian-unstable.list \
	&& echo 'APT::Default-Release "testing";' > /etc/apt/apt.conf.d/default
ENV R_BASE_VERSION 3.4.3
RUN apt-get update \
	&& apt-get install -t unstable -y --no-install-recommends \
		r-base=${R_BASE_VERSION}* \
		r-base-dev=${R_BASE_VERSION}* \
		r-recommended=${R_BASE_VERSION}* \
        && echo 'options(repos = c(CRAN = "https://cran.rstudio.com/"), download.file.method = "libcurl")' >> /etc/R/Rprofile.site \
        && echo 'source("/etc/R/Rprofile.site")' >> /etc/littler.r \
	&& rm -rf /tmp/downloaded_packages/ /tmp/*.rds \
	&& rm -rf /var/lib/apt/lists/*
```

Did you call R via CLI or do you use `rpy2`.

**Comment by nuest** [comment]
**Wait a second**. One more test let's me think: maybe just switch out the base image!

```
~$ docker run --rm -it rocker/verse python3 --version
Python 3.5.3
```

Is `3.5.3` OK for meta?

**Comment by 7048730** [comment]
most parsers will work in 3.5.3 but I was aiming for 3.6

**Comment by nuest** [comment]
Then I suggest to go with the Python base image, because otherwise we depend on Debian updating Python in their repos.

**Comment by 7048730** [comment]
wait, wasn't the purpose of the the chosen debian base image to ensure the availability of the compiling eco system needed to build geo themed python packages? 
so take `3.6-stretch` and install R into it? to read rdata with R, a totally minimal R installation should suffice

**Comment by nuest** [comment]
R is also Debian based, so what we can get to work in `python:3.6-stretch` should work just the same in `rocker/...`.

**Comment by 7048730** [comment]
r base has found its way into o2r-meta dockerfile; issue can be closed
