### ISSUE TITLE
Add metadata validation step before updating

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-muncher#60]
In `compendium.js` function `updateMetadata`:

- [x] Integrate the `validate` tool, see https://github.com/o2r-project/o2r-meta#3-validator-tool so that _only_ valid metadata are saved (and new files generated)
- [x] for publish during tests must use valid metadata now, could be build upon https://github.com/o2r-project/o2r-meta/blob/dev/schema/json/example_metadata_o2r_valid.json (for minimal variant check [the schema](https://github.com/o2r-project/o2r-meta/blob/dev/schema/json/o2r-meta-schema.json) for required properties)
- [x] update API to communicate validation issues with appropriate HTTP code and JSON response
- [x] add a couple of tests with invalid metadata updates

**Comment by 7048730** [comment]
cf. https://github.com/o2r-project/o2r-meta/issues/46#issuecomment-348196073

**Comment by nuest** [comment]
https://github.com/o2r-project/o2r-web-api/commit/9b5ec72b18235fd6ab877e983f2f0c844e41f913

**Comment by nuest** [comment]
Had to make some hacks fixing the metadata included in some tests, but eventually the users will also do that.
